[ various tweaks ][ thu_251211 ][ 09:56pm ][ wisdmm ]

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,7 +4,7 @@ runner () {
     local os="$(uname)"
 
     case "$os" in
-        "Darwin") ./bip && open -a Preview *.bmp ;;
+        "Darwin") ./bip && open *.bmp ;;
         *)
             ./bip
             if command -v nsxiv >/dev/null 2>&1; then
@@ -24,20 +24,36 @@ runner () {
 installer () {
     local bindir="$HOME/.local/bin"
     
-    if [ -d "$bindir" ]; then
-        ln -s bip "$bindir"
-    else
-        mkdir -p "$bindir"
-        ln -s bip "$bindir"
-    fi
+    [ -d "$bindir" ] || mkdir -p "$bindir"
+    cp bip "$bindir"
+    cp ./scripts/bop "$bindir"
 
-    if [ -e "$HOME/.profile" ];
-        echo "export PATH=$HOME/.local/bin:$PATH" >> "$HOME/.profile"
-    fi
+    #if [ -e "$HOME/.profile" ]; then
+    #    echo "export PATH=$HOME/.local/bin:$PATH" >> "$HOME/.profile"
+    #fi
+}
+
+cleaner () {
+    rm *.bmp bip
+}
+
+helper () {
+    printf "\n\033[94m  build [\033[4;92moptions\033[0;93m: run, install, clean\033[0;94m]\033[0m\n"
+    printf "\n\033[96m  this script offers a simple way to compile, run, and install bip.\n"
+    printf "\n  \033[4;92moptions\033[0m:\n\n"
+    printf "      \033[94mbuild         \033[96m| with no options, 'build' compiles the program, runs it, and opens the resulting image.\n"
+    printf "      \033[94mbuild \033[93mrun     \033[96m| runs the program and opens the resulting image (it must be compiled first).\n"
+    printf "      \033[94mbuild \033[93minstall \033[96m| moves the program from the current directory to the user's ~/.local/bin directory.\n"
+    printf "      \033[94mbuild \033[93mclean   \033[96m| removes the image files and binary from this directory.\n"
+    printf "      \033[94mbuild \033[93mhelp    \033[96m| displays this help message.\n"
+    printf "\n\033[0m"
 }
 
 case "$1" in
     "") cc -o bip bip.c && runner ;;
     "run") runner ;;
-    "clean") rm *.bmp bip ;;
+    "clean") cleaner ;;
+    "install") installer && cleaner || echo "couldn't complete install." ;;
+    "help") helper ;;
+    *) printf "unknown option: $1\n\nusage:\n" && helper ;;
 esac
